---
title: "Prior Elicitation Results"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include = FALSE} 
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, fig.height = 3, comment = "")
```




<!--- user inputs -->
## User Inputs
```{r}
inputs <- data.frame("." = c(input$data_model, input$n),
                     row.names = c("Data Model", "Observations  ")
)
cat(capture.output(inputs)[-1], sep = "\n")
invisible(inputs)
```




<!--- elicited prior information -->

<!--- joint prior -->
## Elicited Prior -- Joint

### Family
```{r}
cat("Normal-Inverse-Gamma", sep = "\n")
```


### Parameters
```{r}
cat(capture.output(bag$hyper_params_joint)[-1], sep = "\n")
invisible(bag$hyper_params_joint)
```


<!--- prior for mean -->
## Elicited Prior -- Mean (Conditional on Variance)

### Family
```{r}
cat("Normal", sep = "\n")
```


### Parameters
```{r}
cat(capture.output(bag$hyper_params_mean)[-1], sep = "\n")
invisible(bag$hyper_params_mean)
```
Note: (Sigma^2)* = Mode of Inverse-Gamma prior on Sigma^2


### Summaries
```{r}
cat(capture.output(bag$summaries_mean)[-1], sep = "\n")
invisible(bag$summaries_mean)
```


### Plot
```{r}
bag$p_plot_mean + theme(plot.title = element_text(size = 11),
	axis.title = element_text(size = 11), axis.text = element_text(size = 10))
```


<!--- prior for variance -->
## Elicited Prior -- Variance

### Family
```{r}
cat("Inverse-Gamma", sep = "\n")
```

### Parameters
```{r}
cat(capture.output(bag$hyper_params_var)[-1], sep = "\n")
invisible(bag$hyper_params_var)
```


### Summaries
```{r}
cat(capture.output(bag$summaries_var)[-1], sep = "\n")
invisible(bag$summaries_var)
```


### Plot
```{r}
bag$p_plot_var + theme(plot.title = element_text(size = 11),
	axis.title = element_text(size = 11), axis.text = element_text(size = 10))
```


<!--- number of selections and history plots -->
## Other

### Number of Selections -- Mean
```{r}
cat(capture.output(bag$n_mean_selections)[-1], sep = "\n")
invisible(bag$n_mean_selections)
```

### Number of Selections -- Variance
```{r}
cat(capture.output(bag$n_var_selections)[-1], sep = "\n")
invisible(bag$n_var_selections)
```


### History Plots
```{r}
ggplot() +
	geom_point(data = bag$store_normal_mean_mesh, aes(x = step, y = intervals)) + 
	geom_point(data = bag$store_normal_mean_selected, aes(x = step, y = selected_param, 
		color = "red")) +
	geom_line(data = bag$store_normal_mean_selected, aes(x = step, y = selected_param, 
		color = "red")) +
	scale_x_continuous(limits = c(0, bag$mean_counter), breaks = seq(0, bag$mean_counter, 
		by = 10)) +
	labs(x = "Selection Number", y = expression(mu), 
		title = "Red:    Selected parameter\nBlack:  Unselected parameter") +
	theme(plot.title = element_text(size = 11, hjust = 0), 
		axis.title.x = element_text(size = 11, margin = margin(15, 0, 0, 0)), 
    axis.title.y = element_text(size = 11, margin = margin(0, 10, 0, 0)),
		axis.text = element_text(size = 10), 
		legend.position = "none")

ggplot() +
	geom_point(data = bag$store_normal_var_mesh, aes(x = step, y = intervals)) + 
	geom_point(data = bag$store_normal_var_selected, aes(x = step, y = selected_param, 
		color = "red")) +
	geom_line(data = bag$store_normal_var_selected, aes(x = step, y = selected_param, 
		color = "red")) +
	scale_x_continuous(limits = c(0, bag$var_counter), breaks = seq(0, bag$var_counter, 
		by = 10)) +
	labs(x = "Selection Number", y = expression(sigma^2), 
		title = "Red:    Selected parameter\nBlack:  Unselected parameter") +
	theme(plot.title = element_text(size = 11, hjust = 0), 
		axis.title.x = element_text(size = 11, margin = margin(15, 0, 0, 0)), 
    axis.title.y = element_text(size = 11, margin = margin(0, 10, 0, 0)),
		axis.text = element_text(size = 10), 
		legend.position = "none")
```



